[project]
name = "greenhouse-ontology"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LiamYS", email = "lvlaskamp@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "google-genai>=2.23.0",
    "openai>=3.13.0",
    "pymupdf4llm>=1.28.2",
    "rdflib>=7.6.0",
]

[project.scripts]
greenhouse-ontology = "greenhouse_ontology:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
